version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: test

      - image: circleci/postgres:9.4
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install bundler
          command: gem install bundler -v $(tail -1 Gemfile.lock | tr -d ' ')

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec --format progress
